name: Twitter Bot

on:
  schedule:
    - cron: '30 3,7,9,11,13,21,23 * * *' # UTC

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Python 3
      run: |
        sudo apt-get update
        sudo apt-get install python3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy

    - name: Run script
      env:
        BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      run: python tweet.py